# -*- coding: utf-8 -*-
"""Project2_StudentGradeReport.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12VIbTIC9oiQPAfSE1j-VCs_Ouw-C7ecn
"""

# square pattern with numbers

# Step 1: Ask for size
size = int(input("Enter the size: "))

# Step 2: Loop through rows
for row in range(1, size + 1):

    # First and last row → print all numbers
    if row == 1 or row == size:
        for col in range(1, size + 1):
            print(col, end=" ")
    else:
        # Middle rows → 1, spaces, size
        print(1, end=" ")

        # spaces in between (numbers replaced by tabs)
        for space in range(size - 2):
            print(" ", end=" ")

        print(size, end=" ")

    # move to next line after each row
    print()