# -*- coding: utf-8 -*-
"""Project1_DailyExpenseCalculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CHBLelb8zdimAjk0lBQ44Ncd2T2qEGuj
"""

# Daily Income and Expense Tracker

# Step 1: Ask user for daily income
income = float(input("Enter your daily income: "))

# Step 2: Initialize expenses to zero
total_expenses = 0.0

# Step 3:asking for expenses until the user types 'done'
while True:
    expense = input("Enter an expense (or 'done' to finish): ")

    # if user finishes entering expenses
    if expense.lower() == "done":
        break

    # convert expense to number and add to total
    try:
        total_expenses += float(expense)
    except ValueError:
        print("Invalid input. Please enter a number or 'done'.")

# Step 4: Calculate remaining balance
balance = income - total_expenses

# Step 5: Show results
print("\nTotal Income:", income)
print("Total Expenses:", total_expenses)
print("Remaining Balance:", balance)

# Step 6: Show message based on spending
if total_expenses < income:
    print("You saved money today!")
elif total_expenses > income:
    print("You overspent today!")
else:
    print("You spent exactly your income today!")